### ISSUE TITLE
Replace TODO:{import,export} with proper implementations

### ISSUE THREAD

**Issue by RReverser** [RReverser/esmod#2]
@jdalton Assigning you as I think that one won't require any parser-specific help from me.

**Comment by jdalton** [comment]
Currently, this WIP acorn plugin takes code like:
```js
import 'smth';
while (1) {
  /* looks like block, but it's not: {
  } */
  smth
}
export const answer = 42;
```
and transforms it into:
```js
<TODO:import>
while (1) {
  /* looks like block, but it's not: {
  } */
  smth
}
<TODO:export>
```

My plan was to base the transform off of [transform-es2015-modules-commonjs](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-modules-commonjs/src/index.js) and [add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports). I'm not super proficient with AST transforms so if anyone else wants to jump in, please be my guest.

We should make the transform customizable so it can be tailored for folks like Webpack.
Pinging in @TheLarkInn.

**Comment by jdalton** [comment]
Pinging in @TheLarkInn

**Comment by jdalton** [comment]
We may make the transform customizable so it can be tailored for folks like Webpack.

**Comment by bmeck** [comment]
use https://github.com/babel/babel/pull/4964 if you want a closer to real implementation (but still not proper w/ cache, URL pathing, and some other behavior)

**Comment by jdalton** [comment]
@bmeck  Thanks for the reference! I'm cool with it being more simple, hand wavy, and loose at the moment. This project started out of a gist yesterday so I trying not to kill it with complexity right off the bat. Webpack will likely have a transform in mind, as I have. Being a spec perfect clone isn't on my radar right now.

**Comment by jdalton** [comment]
Moving to #3.
