### ISSUE TITLE
Dynamic import support

### ISSUE THREAD

**Issue by guybedford** [RReverser/esmod#4]
@RReverser you may know if it's possible to add a tokenizing phase that can just spit out this part of the AST with location information and the ability to transform?

Ideally then the transform should be something like:

```javascript
import('x').then(m => ...);
// ->
Promise.resolve(require('x')).then(x => x && x.__esModule ? x : { default: x }).then(m => ...);
```

**Comment by RReverser** [comment]
Nope, this one can appear pretty much anywhere as it's just an expression, so we can't use same tricks with skipping entire blocks of code.

**Comment by guybedford** [comment]
But is `import` seen as an identifier during tokenizing? It's a reserved identifier name so that would be the only meaning, perhaps making some trick possible here?

**Comment by RReverser** [comment]
Hmm yeah maybe, given that it's reserved is helpful indeed. Should be possible albeit more complicated.

**Comment by RReverser** [comment]
TBH I've already spent somewhat more time here that initially planned - it was supposed to be just an experiment to answer @jdalton's enquiry about whether it's possible to parse only top-level stuff for performance :)

Maybe I'll play somewhat more to improve performance further, but I don't want to invest too much time in other syntaxes - no offence. Feel free to send PRs though.

**Comment by RReverser** [comment]
Actually realized there are cases where it still wouldn't be possible with just tokenizer (without correct tracking of statement/expression/... contexts). For example:

```javascript
var obj = {
  import(x) {
    ...
  }
};
```

is completely valid JavaScript that defines a shorthand method `import` with parameter `x` but pure pattern matching on top of tokenizer would find it as `import(x)` expression. It would require adding bunch of rules on top of such pattern matching to distinguish them precisely and might get way too involved compared to regular parsing.

**Comment by jdalton** [comment]
@RReverser 
> Maybe I'll play somewhat more to improve performance further, but I don't want to invest too much time in other syntaxes - no offence. Feel free to send PRs though.

Seriously thank you!

@guybedford

I think dynamic `import()` support may be out of scope for this top-level only parse.
~~I figured the `import()` helper could be added at the top of a file w/o having to transpile individual calls.~~

Ah `import` is a reserved word so adding a helper at the top of a file wouldn't work.
I still think that falls to a more robust parse (more than just top level).

**Comment by jdalton** [comment]
Ah `import` is a reserved word. So adding a helper at the top of a file wouldn't work.
I still think that falls into a more robust parse (more than just top level).
