### ISSUE TITLE
Adapt tokenizing for module detection in resolution

### ISSUE THREAD

**Issue by guybedford** [RReverser/esmod#5]
It would be good to get a variation of the tokenizing that can be used for an early stage detection (can the AST from this early stage then be reused for the transform stage or does it still result in a double parse?).

The process of supporting both CJS and ESM then falls pretty simply from that detection process.

**Comment by RReverser** [comment]
This sounds like rather related to https://github.com/bmeck/UnambiguousJavaScriptGrammar proposal with its known shortcomings (like ESM without `import` / `export` are still ESM as per spec, but can't be automatically detected). This required changes in spec to be possible, but wasn't adopted.

**Comment by RReverser** [comment]
Closing as implementing detection is the easiest part of such proposal, but spec changes are a blocker.

**Comment by jdalton** [comment]
As a co-author of Unambiguous JavaScript Grammar that would be rad. In the proposal [there's a section outlining folks who could benefit from ujsg](https://github.com/bmeck/UnambiguousJavaScriptGrammar#external-examples-and-impact) so providing an optimized path would :metal: and it doesn't require a spec change. That said, I think maybe that's an issue to raise over on [acorn's repo](https://github.com/ternjs/acorn) and not this one.

**Comment by RReverser** [comment]
@jdalton What I'm saying is detection is already easy with plugin as implemented here, but until it's part of the spec, it's not going to be reliable as we would be breaking spec when parsing code that is ambiguously either sloppy script or module without imports/exports (ambiguous due to strict mode having impact on how things should be parsed).
